{
 "title": "Custom Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Node readiness status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "K8S node status",
   "type": "gauge",
   "description": "Shows the node readiness status",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",status=\"true\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Pod status in Onap namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"onap\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"onap\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"onap\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"onap\", phase=\"Failed\"})"
    }
   ]
  },
  { "title": "Open file descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Open file descriptors",
   "type": "graph",
   "description": "Number of currently opened file descriptors",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "open fds" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Open file descriptors usage",
   "type": "graph",
   "description": "Percentage of total available file descriptors allocated",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent", "label": "open fds" }
   ],
   "targets": [
    {
     "expr": "(node_filefd_allocated/node_filefd_maximum)*100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}