{
 "title": "Galera/MariaDB",
 "tags": [
  "galera",
  "mariadb",
  "onap"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "Service uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_global_status_uptime", "legendFormat": "{{ pod }}" }
   ]
  },
  {
   "title": "Active Connections with max value",
   "type": "bargauge",
   "description": "Displays current active connections count and configured maximum value",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "{{ pod }} (current)"
    },
    {
     "expr": "mysql_global_variables_max_connections",
     "legendFormat": "{{ pod }} (max)"
    }
   ]
  },
  { "title": "Connections/Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Shows number of open connections and max used connections",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Active Connections - {{ pod }}"
    },
    {
     "expr": "mysql_global_status_max_used_connections",
     "legendFormat": "Max Used Connections - {{ pod }}"
    }
   ]
  },
  {
   "title": "SQL QPS",
   "type": "graph",
   "description": "SQL command query rate per second (5m averages)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "description": "Top 5 sql commands over 5 minute time frames by each replica",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(mysql_global_status_commands_total[5m]))",
     "legendFormat": "{{ command }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_slow_queries[1m])",
     "legendFormat": "Slow Queries on {{ pod }}"
    }
   ]
  },
  {
   "title": "Aborted Connections/Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_aborted_connects[1m])",
     "legendFormat": "Aborted Connects - {{ pod }}"
    },
    {
     "expr": "irate(mysql_global_status_aborted_clients[1m])",
     "legendFormat": "Aborted Clients  - {{ pod }}"
    }
   ]
  },
  { "title": "System stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Open Files",
   "type": "graph",
   "description": "Shows the number of open files",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_global_status_open_files", "legendFormat": "Open Files - {{ pod }}" },
    {
     "expr": "mysql_global_status_innodb_num_open_files",
     "legendFormat": "InnoDB Open Files - {{ pod }}"
    }
   ]
  },
  {
   "title": "Network received vs sent",
   "type": "graph",
   "description": "Network received vs sent in 5m averages",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received[5m])",
     "legendFormat": "received - {{ pod }}"
    },
    {
     "expr": "irate(mysql_global_status_bytes_sent[5m])",
     "legendFormat": "sent - {{ pod }}"
    }
   ]
  },
  {
   "title": "Disk reads vs writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_reads[10m])",
     "legendFormat": "reads - {{ pod }}"
    },
    {
     "expr": "irate(mysql_global_status_innodb_data_writes[10m])",
     "legendFormat": "write - {{ pod }}"
    }
   ]
  }
 ]
}