---
- name: Setup resolv.conf for node to find package repository by name from infra
  lineinfile:
    line: "nameserver {{ hostvars[groups.infrastructure[0]].cluster_ip }}"
    path: /etc/resolv.conf
    state: present
    insertbefore: BOF
  become: yes

- name: Add application offline package repository and disable all others
  yum_repository:
    name: "{{ item.name }}"
    file: "{{ item.file }}"
    description: "{{ item.description | default('') }}"
    baseurl: "{{ item.baseurl | default('') }}"
    gpgcheck: "{{ item.gpgcheck | default(true) }}"
    enabled: "{{ item.enabled | default(false) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ yum_repositories }}"
  become: yes
