---
- name: Setup resolv.conf for node to find package repository by name from infra
  lineinfile:
    line: "nameserver {{ hostvars[groups.infrastructure[0]].cluster_ip }}"
    path: /etc/resolv.conf
    state: present
    insertbefore: BOF
    unsafe_writes: true

- name: Disable all default repositories
  block:
    - name: Find repo files names - CentOS
      find:
        paths: "{{ repo_path[ansible_os_family] }}"
        pattern: "{{ repo_patern[ansible_os_family] }}"
      register: repo_files

    - name: Get all defined offline repo names
      set_fact: package_repositories_names="{{ package_repositories | selectattr('name', 'defined') | map(attribute='name') | list  }}"

    - name: Backup repo files
      copy:
        remote_src: true
        src: "{{ item.path }}"
        dest: "{{ item.path }}.disabled"
      loop: "{{ repo_files.files }}"
      when: "(item.path | basename | splitext)[0] not in package_repositories_names"

    - name: Remove disabled repo files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ repo_files.files }}"
      when: "(item.path | basename | splitext)[0] not in package_repositories_names"

- include_tasks: "{{ ansible_os_family }}.yml"
