---
- name: Setup resolv.conf for node to find package repository by name from infra
  lineinfile:
    line: "nameserver {{ hostvars[groups.infrastructure[0]].cluster_ip }}"
    path: /etc/resolv.conf
    state: present
    insertbefore: BOF
    unsafe_writes: true

- name: Disable all CentOS default repositories
  block:
    - name: Find repo files names - yum
      find:
        paths: /etc/yum.repos.d
        pattern: '*.repo'
      register: repo_files

    - name: Get all defined offline repo names
      set_fact: package_repositories_names="{{ package_repositories | selectattr('name', 'defined') | map(attribute='name') | list  }}"

    - name: Backup repo files - yum
      copy:
        remote_src: true
        src: "{{ item.path }}"
        dest: "{{ item.path }}.disabled"
      loop: "{{ repo_files.files }}"
      when: "(item.path | basename | splitext)[0] not in package_repositories_names"

    - name: Remove disabled repo files - yum
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ repo_files.files }}"
      when: "(item.path | basename | splitext)[0] not in package_repositories_names"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Disable all Ubuntu OS default repositories
  block:
    - name: Find repo files names - apt
      find:
        paths: /etc/apt/
        pattern: '*.list'
      register: repo_files

    - name: Get all defined offline repo names - apt
      set_fact: package_repositories_names="{{ package_repositories | selectattr('name', 'defined') | map(attribute='name') | list  }}"

    - name: Backup repo files - apt
      copy:
        remote_src: true
        src: "{{ item.path }}"
        dest: "{{ item.path }}.disabled"
      loop: "{{ repo_files.files }}"
      when: "(item.path | basename | splitext)[0] not in package_repositories_names"

    - name: Remove disabled repo files - apt
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ repo_files.files }}"
      when: "(item.path | basename | splitext)[0] not in package_repositories_names"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add application offline package repository - yum
  yum_repository:
    name: "{{ item.name }}"
    file: "{{ item.file }}"
    description: "{{ item.description | default('') }}"
    baseurl: "{{ item.baseurl | default('') }}"
    gpgcheck: "{{ item.gpgcheck | default(true) }}"
    enabled: "{{ item.enabled | default(false) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ package_repositories }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add application offline package repository - apt
  apt_repository:
    repo: "deb [trusted=yes] {{ item.baseurl | default('') }} stable main"
    state: "{{ item.state | default('present') }}"
    validate_certs: true
    filename: "{{ item.file }}"
    update_cache: false
  loop: "{{ package_repositories }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
