---
- name: Setup resolv.conf for node to find package repository by name from infra
  lineinfile:
    line: "nameserver {{ hostvars[groups.infrastructure[0]].cluster_ip }}"
    path: /etc/resolv.conf
    state: present
    insertbefore: BOF
  become: true

- name: Disable all OS default repositories
  block:
    - name: Find repo files names
      find:
        paths: /etc/yum.repos.d
        pattern: '*.repo'
      register: repo_files

    - name: Get all defined offline repo names
      set_fact: package_repositories_names="{{ package_repositories | selectattr('name', 'defined') | map(attribute='name') | list  }}"

    - name: Backup repo files
      copy:
        remote_src: yes
        src: "{{ item.path }}"
        dest: "{{ item.path }}.disabled"
      loop: "{{ repo_files.files }}"
      when: "(item.path | basename | splitext)[0] not in package_repositories_names"

    - name: Remove disabled repo files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ repo_files.files }}"
      when: "(item.path | basename | splitext)[0] not in package_repositories_names"
  become: true

- name: Add application offline package repository
  yum_repository:
    name: "{{ item.name }}"
    file: "{{ item.file }}"
    description: "{{ item.description | default('') }}"
    baseurl: "{{ item.baseurl | default('') }}"
    gpgcheck: "{{ item.gpgcheck | default(true) }}"
    enabled: "{{ item.enabled | default(false) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ package_repositories }}"
  become: true

# yum module doesnt support querying from particular repo
# also its important to clean cache as it can hide potential problem
- name: Clean cache and check health of offline package repository block
  block:
    - name: Clean yum cache
      command: yum clean all
      args:
        warn: False # yum module is insufficient
      changed_when: false

    - name: Remove yum cache
      file:
        path: /var/cache/yum
        state: absent

    - name: Check offline package repos
      command: "yum repo-pkgs {{ item.name }} list"
      args:
        warn: False # yum module is insufficient
      changed_when: false
      loop: "{{ package_repositories }}"
  become: true

