---
- name: Setup resolv.conf for node to find package repository by name from infra
  lineinfile:
    line: "nameserver {{ hostvars[groups.infrastructure[0]].cluster_ip }}"
    path: /etc/resolv.conf
    state: present
    insertbefore: BOF
    unsafe_writes: true

- include_tasks: rhel.yml
  when: ansible_distribution in ["CentOS","Red Hat Enterprise Linux"]

- include_tasks: ubuntu.yml
  when: ansible_distribution in ["Ubuntu","Debian"]
