---
- name: Setup resolv.conf for node to find package repository by name from infra
  lineinfile:
    line: "nameserver {{ hostvars[groups.infrastructure[0]].cluster_ip }}"
    path: /etc/resolv.conf
    state: present
    insertbefore: BOF
  become: true

- name: Add application offline package repository
  yum_repository:
    name: "{{ app_name }}"
    file: "{{ app_name | lower }}"
    description: "{{ app_name | upper }} offline repository"
    baseurl: "{{ 'http://repo.infra-server/rhel' if 'infrastructure' not in group_names else 'file://' + app_data_path + '/pkg/rhel' }}"
    gpgcheck: false
    enabled: true
  when: deploy_package_repository
  become: true
