#cloud-config
#Enable root login.
disable_root: false
#Output everything to /dev/console...
output: { all: "/dev/console" }
#Clear /etc/resolv.conf
bootcmd:
  - echo > /etc/resolv.conf
#Initialization.
runcmd:
  - |
    set -efxu
    %{NOTIFY_COMMAND} --data-binary '{"status": "SUCCESS", "reason": "instance started successfully"}'
