#cloud-config
#Enable root login.
disable_root: false
#Output everything to /dev/console...
output: { all: "/dev/console" }
manage_resolv_conf: false
#Initialization.
runcmd:
  - |
    set -efxu
    %{NOTIFY_COMMAND} --data-binary '{"status": "SUCCESS", "reason": "instance started successfully"}'
