---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: infrastructure-server
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-ubuntu}:${PREBUILD_DISTRO_VERSION:-18.04}
    pre_build_image: True
    privileged: true
    override_command: False
    groups:
      - infrastructure
    volumes:
      - /var/lib/docker
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
    ANSIBLE_LIBRARY: ../../../../library
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    cleanup: ../default/cleanup.yml
  inventory:
    host_vars:
      infrastructure-server:
        cluster_ip: 127.0.0.1
verifier:
  name: testinfra
