---
- name: Extract root certificate - Rhel/CentOS
  command: /usr/bin/update-ca-trust extract
  changed_when: true  # this handler is executed just when there is a new cert
  notify: Restart Docker
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Extract root certificate - Ubuntu
  command: update-ca-certificates
  changed_when: true
  notify: Restart Docker
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
