---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: infrastructure-server
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-centos}:${PREBUILD_DISTRO_VERSION:-centos7.6}
    pre_build_image: True
    privileged: true
    volumes:
      - /var/lib/docker
    override_command: False
    groups:
      - infrastructure
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
  inventory:
    links:
      group_vars: ../../../../group_vars
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    v: 1
