---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: instance
    image: ${PLATFORM_DISTRO:-ubuntu}:${DISTRO_VERSION:-18.04}
    dockerfile: ../default/Dockerfile.j2
provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
scenario:
  name: ubuntu
verifier:
  name: testinfra
  directory: ../default/tests/
