---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Include infrastructure group variables
      include_vars: ../../../../group_vars/infrastructure.yml
  tasks:
    - name: "Include cert-manager"
      include_role:
        name: "cert-manager"
