---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Include infrastructure group variables
      include_vars: ../../../../group_vars/infrastructure.yml
  roles:
    - cert-manager
    - role: bash-completion
      completion_bin: cmctl
