---
- name: Install python2-openshift  # community.kubernetes.k8s module dependency
  package:
    name: python2-openshift
    state: present
  when: ansible_os_family == "RedHat"

- name: Install pip
  package:
    name: python3-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Install OpenShift Python client library
  pip:
    name: openshift
  environment:
    PIP_DISABLE_PIP_VERSION_CHECK: 1
  when: ansible_os_family == "Debian"

- name: Check volumes config
  debug:
    msg: "k8s volumes: {{ k8s_volumes }}"

- name: Create k8s persistent volumes
  community.kubernetes.k8s:
    wait: True
    template: pv.yaml.j2
  loop: "{{ k8s_volumes }}"

- name: Create host paths for PVs and set their permissions
  file:
    path: "{{ item.path_prefix }}/{{ item.name }}"
    state: directory
    owner: "{{ item.owner | default(0) }}"
    group: "{{ item.group | default(0) }}"
  loop: "{{ k8s_volumes }}"
