---
- name: "Set cluster_ip"
  hosts: all
  tasks:
    - name: "Set cluster_ip fact"
      set_fact:
        cluster_ip: "{{ ansible_default_ipv4.address }}"

- name: Configure kubernetes cluster (RKE)
  hosts: infrastructure
  roles:
    - role: rke
      vars:
        rke_dns:
          provider: coredns
          upstreamnameservers:
            - 8.8.8.8
        mode: config

- name: Prepare kubernetes hosts (RKE)
  hosts: kubernetes
  roles:
    - role: rke
      vars:
        mode: node

- name: Deploy kubernetes cluster (RKE)
  hosts: infrastructure
  roles:
    - role: rke
      vars:
        mode: deploy
