---
- name: Check cluster health
  uri:
    url: "{{ rancher_server_url }}/v2-beta/projects/{{ k8s_env_id }}"
  register: env_info
  retries: 30
  delay: 15
  until: "env_info.json.healthState == 'healthy'"
