---
# This group contains hosts with all resources (binaries, packages, etc.)
# in tarball.
all:
  vars:
    #This is the subnet where kubernetes nodes and infra server communicate.
    kubernetes_subnet: 10.8.8.0/24
    # this key is supposed to be generated during setup.yml playbook execution
    # change it just when you have better one working for all nodes
    ansible_ssh_private_key_file: /root/.ssh/offline_ssh_key
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    resources:
      hosts:
        resource-host:
          ansible_host: 10.8.8.5

    # This is group of hosts where nexus, nginx, dns and all other required
    # services are running.
    infrastructure:
      hosts:
        infrastructure-server:
          ansible_host: 10.8.8.13

    # This is group of hosts which are/will be part of Kubernetes cluster.
    kubernetes:
      hosts:
        kubernetes-node-1:
          ansible_host: 10.8.8.19

    nfs-server:
      hosts:
        kubernetes-node-1
