---
- name: Generate certs
  import_tasks: generate-certificates.yml
  delegate_to: localhost

- name: Upload certificates to infrastructure server
  copy:
    src: "{{ certificates_tmp_dir }}"
    directory_mode: true
    dest: "{{ app_data_path }}/"

- import_tasks: upload_root_ca.yml
