---
- name: Create a rke user on the node
  user:
    name: "{{ rke_username }}"
    groups: docker
    password_lock: yes

- name: Distribute rke user ssh public key
  authorized_key:
    user: "{{ rke_username }}"
    key: "{{ hostvars[groups['infrastructure'][0]].cluster_public_key }}"
