---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: instance
    image: ${PLATFORM_DISTRO:-centos}:${DISTRO_VERSION:-7}
provisioner:
  name: ansible
verifier:
  name: testinfra
