---
- name: Setup values for ONAP deployment
  template:
    src: values.yaml.j2
    dest: "{{ app_helm_charts_infra_directory }}/onap/values.yaml"

- name: Patch OOM - nexus domain resolving
  lineinfile:
    path: "{{ app_helm_charts_infra_directory }}/{{ item }}"
    regexp: '^(.*)HOSTS_FILE_RECORD'
    line: '\g<1>{{ cluster_ip }} {{ simulated_hosts.nexus | join(" ") }} >> /etc/hosts;'
    backrefs: yes
    state: present
  with_items:
    - common/dgbuilder/templates/deployment.yaml
    - sdnc/charts/sdnc-portal/templates/deployment.yaml

- name: Patch OOM - set npm registry
  lineinfile:
    path: "{{ app_helm_charts_infra_directory }}/{{ item }}"
    regexp: '^(.*)NPM_REGISTRY_RECORD'
    line: '\g<1>npm set registry "http://nexus.{{ ansible_nodename }}/repository/npm-private/";'
    backrefs: yes
    state: present
  with_items:
    - common/dgbuilder/templates/deployment.yaml
    - sdnc/charts/sdnc-portal/templates/deployment.yaml
