---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Include kubernetes group variables
      include_vars: ../../../../group_vars/kubernetes.yml
  tasks:
    - name: "Include k8s-persistent-volume"
      include_role:
        name: "k8s-persistent-volume"
