---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
  inventory:
    group_vars:
      all:
        app_helm_override_file: "/override.yml"
verifier:
  name: testinfra
