---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: bash-completion
    pull: false
    image: centos:7
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
    ANSIBLE_LIBRARY: ../../../../library
  inventory:
    group_vars:
      all:
        test: 1
verifier:
  name: testinfra
