---
- name: Prepare infra container to play strimzi-kafka-operator role
  hosts: all
  pre_tasks:
    - name: Include infrastructure group variables
      include_vars: ../../../../group_vars/infrastructure.yml
  tasks:
    - name: "Include prepare-strimzi-kafka-operator role"
      include_role:
        name: "prepare-strimzi-kafka-operator"
