---
# Role for generating Helm override.yml file
- name: Register root certificate
  slurp:
    src: "{{ playbook_dir }}/certs/rootCA.crt"
  register: root_cert
  delegate_to: localhost

- name: "set root ca certificate"
  set_fact:
    overrides: "{{ overrides | default({}) | combine({'global': {'cacert': root_cert.content | b64decode}}, recursive=True) }}"

- name: create override.yaml
  copy:
    dest: "{{ app_helm_override_file }}"
    content: "{{ overrides | to_nice_yaml }}"
