---
- name: Install kubectl
  copy:
    src: "{{ app_data_path }}/downloads/kubectl"
    dest: "{{ kubectl_bin_dir }}/kubectl"
    remote_src: true
    mode: 0755

- name: Generate shell autocompletion code for kubectl
  command: kubectl completion bash
  register: kubectl_completion
  changed_when: false

- name: Ensure bash completion dir exists
  file:
    path: "{{ kubectl_completion_dir }}"
    state: directory
    mode: 0755

- name: Install bash autocompletion code for kubectl
  copy:
    content: "{{ kubectl_completion.stdout }}"
    dest: "{{ kubectl_completion_dir }}/kubectl"
    mode: 0644
