---
- name: Stopping docker systemd service
  systemd:
    name: docker
    state: stopped
    enabled: true
  listen: "Restart Docker"

# WA for docker bug, see OOM-1735
- name: Ensure docker.sock cleaned properly
  file:
    state: absent
    path: /var/run/docker.sock
  listen: "Restart Docker"

- name: Starting docker systemd service
  systemd:
    name: docker
    state: started
    enabled: true
  listen: "Restart Docker"
