---
nfs_packages:
  RedHat:
    - nfs-utils
  Debian:
    - nfs-common
    - nfs-kernel-server
nfs_services:
  RedHat:
    - rpcbind
    - nfs-server
  Debian:
    - rpcbind
    - nfs-kernel-server
nfs_destination:
  RedHat:
    - "/etc/exports.d/dockerdata-nfs.exports"
  Debian:
    - "/etc/exports"
