---
k8s_volumes:
  - name: kube-prometheus-prometheus
    capacity: "20Mi"
    path_prefix: "{{ nfs_mount_path }}/kube-prometheus"
    owner: 1000  # derived from prometheus.prometheusSpec.securityContext.runAsUser
    group: 2000  # derived from prometheus.prometheusSpec.securityContext.fsGroup
  - name: kube-prometheus-grafana
    capacity: "25Mi"
    path_prefix: "{{ nfs_mount_path }}/kube-prometheus"
