---
k8s_volumes:
  - name: kube-prometheus
    capacity: "6Gi"
    path_prefix: "{{ nfs_mount_path }}"
    owner: 1000  # derived from prometheus.prometheusSpec.securityContext.runAsUser
    group: 2000  # derived from prometheus.prometheusSpec.securityContext.fsGroup
