---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: infrastructure-server
    image: ubuntu:18.04
    groups:
      - infrastructure
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
    ANSIBLE_LIBRARY: ../../../../library
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/playbook.yml
  inventory:
    group_vars:
      all:
        app_name: onap
        app_data_path: "/opt/{{ app_name }}"
scenario:
  name: ubuntu
verifier:
  name: testinfra
  lint:
    name: flake8
  directory: ../default/tests
