---

#
# This is example configuration to install offline ONAP.
# See available variables to configure and default values used
# in ../ansible/group_vars/*.yml files.
#
resources_dir: /data
app_name: onap
resources_filename: "offline-{{ app_name }}-4.0.0-resources.tar"
app_data_path: "/opt/{{ app_name }}"
certificates:
  organization_name: Samsung
  state_or_province_name: Poland
  country_name: PL
  locality_name: Krakow
app_helm_build_targets:
  - all
  - onap
app_helm_chart_name: onap
