---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:

  - name: resource-host
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-centos}:${PREBUILD_DISTRO_VERSION:-centos7.9}
    pre_build_image: true
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    groups:
      - resources
    networks:
      - name: resource-data
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      #  - ${HOME}/resource-data:/data:rw  # mount fs from host to get nfs exportfs task working

  - name: infrastructure-server
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-centos}:${PREBUILD_DISTRO_VERSION:-centos7.9}
    pre_build_image: true
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    groups:
      - infrastructure
    networks:
      - name: resource-data
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles/
verifier:
  name: testinfra
