---
yum_repositories:
  - name: "base"
    file: "CentOS-Base"
    state: "absent"
  - name: "updates"
    file: "CentOS-Base"
    state: "absent"
  - name: "extras"
    file: "CentOS-Base"
    state: "absent"
  - name: "{{ app_name }}"
    file: "{{ app_name | lower }}"
    description: "{{ app_name | upper }} offline repository"
    baseurl: "{{ 'http://repo.infra-server/rhel' if 'infrastructure' not in group_names else 'file://' + app_data_path + '/pkg/rhel' }}"
    gpgcheck: no
    enabled: yes
