---
package_repositories:
  - name: "{{ app_name }}"
    file: "{{ app_name | lower }}"
    description: "{{ app_name | upper }} offline repository"
    baseurl: "{{ 'http://repo.infra-server/rpm' if 'infrastructure' not in group_names else 'file://' + app_data_path + '/pkg/rpm' }}"
    gpgcheck: false
    enabled: true
