---
- name: Create storage directory for chartmuseum
  file:
    path: "{{ chartmuseum_storage_dir }}"
    state: directory
    mode: 0777

- name: Load chartmuseum server image
  docker_image:
    name: "{{ chartmuseum_server_image }}"
    load_path: "{{ infra_images_path }}/{{ chartmuseum_server_image_tar }}"
    state: present
    timeout: 120
  notify: Run chartmuseum server container
