---
- name: Install chartmuseum
  copy:
    src: "{{ app_data_path }}/downloads/chartmuseum"
    dest: "{{ helm_bin_dir }}"
    remote_src: true
    mode: 0755

- name: Create storage directory for chartmuseum
  file:
    path: "{{ chartmuseum_storage_dir }}"
    state: directory

- name: Run Helm chart repository
  shell: "{{ helm_bin_dir }}/chartmuseum --storage local --storage-local-rootdir {{ chartmuseum_storage_dir }} -port {{ chartmuseum_port }} > /dev/null 2>&1 &"
  async: 10
  poll: 3
  changed_when: false

- name: Check Helm chart repository is running
  command: pgrep chartmuseum
  changed_when: false
  register: pgrep_out
  failed_when: pgrep_out.rc != 0
