---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
  inventory:
    group_vars:
      all:
        app_name: moleculetestapp
        app_data_path: "/opt/{{ app_name }}"
        app_helm_release_name: "{{ app_name }}"
        app_kubernetes_namespace: "{{ app_name }}"
        app_helm_charts_install_directory: application/helm_charts
        app_helm_plugins_directory: "{{ app_helm_charts_install_directory}}/helm/plugins/"
        app_helm_charts_infra_directory: "{{ app_data_path }}/helm_charts"
        helm_bin_dir: /usr/local/bin
        app_helm_build_targets:
          - all
          - onap
        app_helm_chart_name: "{{ app_name }}"
        application_pre_install_role: application/test-patch-role
        application_post_install_role: application/test-patch-role
        helm_version: v2
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/playbook.yml
    cleanup: ../default/cleanup.yml
scenario:
  name: custom_role
  test_sequence:
    - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
