---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: infra_host-ubuntu
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-ubuntu}:${PREBUILD_DISTRO_VERSION:-18.04}
    pre_build_image: True
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    override_command: False
    groups:
      - infrastructure
  - name: node0-ubuntu
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-ubuntu}:${PREBUILD_DISTRO_VERSION:-18.04}
    pre_build_image: True
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    override_command: False
    groups:
      - kubernetes
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
  inventory:
    group_vars:
      all:
        timesync:
          servers:
            - 0.pool.ntp.org
            - 1.pool.ntp.org
          timezone: Europe/Warsaw
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../external_time_source/playbook.yml
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    v: 1
  directory: ../default/tests/
