---
- name: Create configuration directory
  file:
    path: "{{ app_data_path }}/cfg"
    state: directory

- name: Upload configuration to server
  template:
    src: nginx.conf.j2
    dest: "{{ app_data_path }}/cfg/nginx.conf"

- name: Load nginx image
  docker_image:
    name: own_nginx:{{ own_nginx_version }}
    load_path: "{{ app_data_path }}/offline_data/docker_images_infra/own_nginx_{{ own_nginx_version }}.tar"
    state: present
    timeout: 120

- name: Create nexus network
  docker_network:
    name: nexus_network
    state: present

- name: Start nginx
  docker_container:
    name: own_nginx
    image: own_nginx
    networks:
      - name: nexus_network
    ports: "{{ nginx.ports }}"
    volumes: "{{ nginx.volumes }}"
    state: started
    restart_policy: unless-stopped
