---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Include infrastructure group variables
      include_vars: ../../../../group_vars/infrastructure.yml
  tasks:
    - name: "Include kube-prometheus-stack"
      include_role:
        name: "kube-prometheus-stack"
