---
- name: Perform common environment setup for nodes
  hosts: infrastructure, kubernetes
  roles:
    - package-repository
    - firewall

- name: Setup infrastructure servers
  hosts: infrastructure
  roles:
    - package-repository-check
    - certificates
    - docker
    - dns
    - vncserver
    - nginx
    - chrony
    - nexus

- name: Setup base for Kubernetes nodes
  hosts: kubernetes:!infrastructure
  roles:
    - chrony
    - package-repository-check
    - docker
  tasks:
    - include_role:
        name: certificates
        tasks_from: upload_root_ca.yml
      vars:
        certificates_local_dir: "{{ playbook_dir }}/certs"
