---
- name: Perform common environment setup for nodes
  hosts: infrastructure, kubernetes
  roles:
    - package-repository
    - role: firewall

- name: Setup infrastructure servers
  hosts: infrastructure
  roles:
    - certificates
    - docker
    - dns
    - vncserver
    - nginx
    - nexus

- name: Setup base for Kubernetes nodes
  hosts: kubernetes
  roles:
    - docker
  tasks:
    - import_tasks: roles/certificates/tasks/upload_root_ca.yml
      vars:
        certificates_local_dir: certs
  handlers: # ansible wont find role handler for imported tasks
    - include: roles/certificates/handlers/main.yml
