---
- name: Setup nfs server
  hosts: nfs-server
  roles:
    - role: nfs
      when: groups.kubernetes | length > 1

- name: Setup nfs mounts
  hosts: kubernetes:!nfs-server
  roles:
    - role: nfs
      when: groups.kubernetes | length > 1
