---
- name: Deploy rancher server and create k8s env
  hosts: infrastructure
  roles:
    - role: rancher
      vars:
        mode: server
    - kubectl
    - helm

- name: Deploy rancher agents for kube nodes
  hosts: kubernetes
  roles:
    - role: rancher
      vars:
        mode: agent

- name: Wait for Kubernetes environment to be healthy
  hosts: infrastructure
  roles:
    - role: rancher
      vars:
        mode: health