---
- name: Install binaries for controlling deployment
  hosts: infrastructure
  roles:
    - kubectl
    - helm

- name: Deploy rancher server and create k8s env
  hosts: infrastructure
  roles:
    - rancher
  vars:
     rancher_role: server

- name: Deploy rancher agents
  hosts: kubernetes
  roles:
    - rancher
  vars:
     rancher_role: agent

- name: Wait for Kubernetes environment to be healthy
  hosts: infrastructure
  tasks:
  - name: Check cluster health
    uri:
      url: "{{ rancher_server_url }}/v2-beta/projects/{{ k8s_env_id }}"
    register: env_info
    retries: 30
    delay: 15
    until: "env_info.json.healthState == 'healthy'"
