---
- name: Install kube binaries and rancher server
  hosts: infrastructure
  roles:
    - kubectl
    - helm
    - role: rancher
      vars:
        rancher_role: server

- name: Deploy rancher agents for kube nodes
  hosts: kubernetes
  roles:
    - role: rancher
      vars:
        rancher_role: agent

- name: Wait for Kubernetes environment to be healthy
  hosts: infrastructure
  roles:
    - role: rancher
      vars:
        rancher_role: health