---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: infrastructure-server
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-ubuntu}:${PREBUILD_DISTRO_VERSION:-18.04}
    pre_build_image: true
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    groups:
      - infrastructure
    networks:
      - name: docker_install
    purge_networks: true
    volumes:
      - /var/lib/docker
provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
    ANSIBLE_LIBRARY: ../../../../library
  inventory:
    host_vars:
      infrastructure-server:
        cluster_ip: 1.2.3.4
        remote_tmp: $HOME/.ansible/tmp
scenario:
  name: ubuntu
verifier:
  name: testinfra
  options:
    verbose: true
    options:
      ignore: W291  # trailing whitespace
  directory: ../default/tests/
