---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: infrastructure-server
    image: ${PLATFORM_DISTRO:-ubuntu}:${DISTRO_VERSION:-18.04}
    groups:
      - infrastructure

  - name: kubernetes-node-1
    image: ${PLATFORM_DISTRO:-ubuntu}:${DISTRO_VERSION:-18.04}
    groups:
      - kubernetes

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  inventory:
    host_vars:
      infrastructure-server:
        cluster_ip: 6.5.4.3
verifier:
  name: testinfra
  options:
    v: 1
