---
# This role contains patching logic for OOM charts
# and is valid until OOM-1610 is implemented
- name: Patch OOM - nexus domain resolving
  lineinfile:
    path: "{{ app_helm_charts_infra_directory }}/{{ item }}"
    regexp: '^(.*)HOSTS_FILE_RECORD'
    line: '\g<1>{{ cluster_ip }} {{ simulated_hosts.nexus | join(" ") }} >> /etc/hosts;'
    backrefs: yes
    state: present
  with_items:
    - common/dgbuilder/templates/deployment.yaml
    - sdnc/charts/sdnc-portal/templates/deployment.yaml

- name: Patch OOM - set npm registry
  lineinfile:
    path: "{{ app_helm_charts_infra_directory }}/{{ item }}"
    regexp: '^(.*)NPM_REGISTRY_RECORD'
    line: '\g<1>npm set registry "http://nexus.{{ ansible_nodename }}/repository/npm-private/";'
    backrefs: yes
    state: present
  with_items:
    - common/dgbuilder/templates/deployment.yaml
    - sdnc/charts/sdnc-portal/templates/deployment.yaml

- name: Patch OOM - set cert path for cloudify
  lineinfile:
    path: "{{ app_helm_charts_infra_directory }}/{{ item }}"
    regexp: '^(.*)CERT_PATH'
    line: '\g<1>/etc/pki/ca-trust/source/anchors'
    backrefs: yes
    state: present
  with_items:
    - dcaegen2/charts/dcae-cloudify-manager/templates/deployment.yaml
