---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: infrastructure-server
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-centos}:${PREBUILD_DISTRO_VERSION:-centos7.6}
    pre_build_image: true
    privileged: true
    override_command: false
    groups:
      - infrastructure
      - kubernetes-etcd
      - kubernetes-control-plane
      - kubernetes
  - name: kubernetes-node-1
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-centos}:${PREBUILD_DISTRO_VERSION:-centos7.6}
    pre_build_image: true
    privileged: true
    override_command: false
    groups:
      - kubernetes
      - kubernetes-node
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
    ANSIBLE_LIBRARY: ../../../../library
  inventory:
    group_vars:
      all:
        cluster_config_dir: /opt/onap/cluster
        rke_etcd:
          enabled_custom_etcd_storage: false
          storage_path: /var/lib/etcd-custom
          storage_mountpoint: /var/lib/rancher/etcd-custom
          enabled_unsafe_volatile_storage: true
          tmpfs_size: 5G
  options:
    e: "app_data_path=/opt/onap"
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    destroy: ../default/destroy.yml
verifier:
  name: testinfra
