---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: infrastructure-ubuntu-k8s-persistent-volume
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-ubuntu}:${PREBUILD_DISTRO_VERSION:-18.04}
    pre_build_image: true
    groups:
      - infrastructure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
    ANSIBLE_LIBRARY: ../../../../library
  playbooks:
    converge: ../default/converge.yml
  inventory:
    group_vars:
      all:
        kubectl_install: true
verifier:
  name: testinfra
  directory: ../default/tests/
