---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: infrastructure-server
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-ubuntu}:${PREBUILD_DISTRO_VERSION:-18.04}
    pre_build_image: true
    privileged: true
    override_command: false
    volumes:
      - /var/lib/docker
    groups:
      - infrastructure
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
  inventory:
    links:
      group_vars: ../../../../group_vars
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
