---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: infrastructure-server
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-centos7}:${PREBUILD_DISTRO_VERSION:-latest}
    pre_build_image: true
    privileged: true
    override_command: false
    restart_policy: unless-stopped
    env:
      container: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/rancher:/var/lib/rancher:ro
    groups:
      - infrastructure
    networks:
      - name: rancher

  - name: kubernetes-node-1
    image: molecule-${PREBUILD_PLATFORM_DISTRO:-centos7}:${PREBUILD_DISTRO_VERSION:-latest}
    pre_build_image: true
    privileged: true
    override_command: false
    restart_policy: unless-stopped
    env:
      container: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/rancher:/var/lib/rancher:ro
    groups:
      - kubernetes
    networks:
      - name: rancher

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
    ANSIBLE_LIBRARY: ../../../../library
  inventory:
    group_vars:
      all:
        app_name: onap
        app_data_path: "/opt/{{ app_name }}"
        rancher_server_version: v1.6.22
    # 1) When running with molecule-dev container, use this definition and comment out localhost under host_vars (2)
    hosts:
      all:
        hosts:
          localhost:
            ansible_connection: ssh
            ansible_host: ${LOCALHOST_ANSIBLE_HOST:-""}
            ansible_user: ${LOCALHOST_ANSIBLE_USER:-""}
            ansible_password: ${LOCALHOST_ANSIBLE_PASSWORD:-""}
            ansible_sudo_pass: ${LOCALHOST_ANSIBLE_SUDO_PASS:-""}
            # end of 1)
            # 2) When running with native molecule installation, use this definition and comment out hosts section under inventory (1)
            # host_vars:
            # localhost:
            #   ansible_sudo_pass: ${LOCALHOST_ANSIBLE_SUDO_PASS:-""}
            #   ansible_ssh_pass: ${LOCALHOST_ANSIBLE_PASSWORD:-""}
            # End of 2)
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # --> Action: 'idempotence'
    # ERROR: Idempotence test failed because of the following tasks:
    # * [infrastructure-server] => rancher : Create rancher kubernetes environment
    # * [kubernetes-node-1] => rancher : Add Rancher Agent
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
