---
- name: Converge master
  hosts: infrastructure
  roles:
    - prepare-common
    - role: rancher
      vars:
        mode: server
        rancher_server_url: "http://{{ cluster_ip }}:8080"

- name: Converge
  hosts: kubernetes
  roles:
    - role: rancher
      vars:
        mode: agent

- name: Wait for Kubernetes environment to be healthy
  hosts: infrastructure
  roles:
    - role: rancher
      vars:
        mode: health
        rancher_server_url: "http://{{ cluster_ip }}:8080"
        # Do not get rancher cluster healthy in this env (to be checked),
        # but it's enough in molecule test to verify we get this unhealthy responce
        rancher_cluster_health_state: unhealthy
        rancher_cluster_health_check_retries: 40
