---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: infrastructure-server
    image: centos:7
    groups:
      - infrastructure
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../../test/roles
    ANSIBLE_LIBRARY: ../../../../library
  inventory:
    group_vars:
      all:
        app_name: onap
        app_data_path: "/opt/{{ app_name }}"
scenario:
  name: default
verifier:
  name: testinfra
